services:
  app:
    build:
      context: ./api
      dockerfile: ../docker/back/Dockerfile
    container_name: app
    restart: always
    tty: true
    depends_on:
      - db
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      PHP_IDE_CONFIG: "serverName=Docker"
    working_dir: /var/www/app
    volumes:
      - ./api:/var/www/app
      - ./docker/back/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    tty: true
    depends_on:
      - app
    volumes:
      - ./api:/var/www/app
      - ./docker/back/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gallery
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - gallery-postgres-data:/var/lib/postgresql/data
    networks:
      - app-network


  redis:
    image: redis
    container_name: redis
    depends_on:
      - app
    restart: always
    tty: true
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    networks:
      - app-network

  node:
    build:
      context: ./client
      dockerfile: ../docker/front/Dockerfile
    container_name: node
    depends_on:
      - app
    restart: always
    tty: true
    ports:
      - 3001:3001
    volumes:
      - ./client:/app
      - '/client/node_modules'
    stdin_open: true

networks:
  app-network:
    driver: bridge
    external: true

volumes:
  gallery-postgres-data:
  redisdata:
    driver: local
